'use strict';
(async()=>{
const $=id=>document.getElementById(id), stage=$('stage'), canvas=$('canvas'), slide=$('slide'), overlays=$('overlays'), overview=$('overview'), status=$('status');
let data,index=-1,request=0,timer,start,notesWindow;const cache=new Map();
function load(i){if(i<0||i>=data.slides.length)return; if(!cache.has(i)){const img=new Image();img.src=data.slides[i].image;cache.set(i,{img,ready:img.decode()});}return cache.get(i);}
function activity(){document.body.classList.add('active');clearTimeout(timer);timer=setTimeout(()=>document.body.classList.remove('active'),1800);}
function position(el,rect){for(const key of ['x','y','width','height'])el.style[{x:'left',y:'top',width:'width',height:'height'}[key]]=rect[key]*100+'%';}
async function render(){const token=++request;let wanted=Number((location.hash.match(/^#slide-(\d+)$/)||[])[1])||1;wanted=Math.max(1,Math.min(data.slides.length,wanted));if(location.hash!==`#slide-${wanted}`)history.replaceState(null,'',`#slide-${wanted}`);const next=wanted-1;try{await load(next).ready;}catch(e){status.textContent='Could not load slide. Check local assets and reload.';return;}if(token!==request)return;overlays.querySelectorAll('video,audio').forEach(m=>m.pause());index=next;const s=data.slides[index];slide.src=load(index).img.src;slide.alt=`Slide ${index+1}`;overlays.replaceChildren();for(const m of s.media){const el=document.createElement(m.kind);el.src=m.src;el.controls=false;el.tabIndex=0;el.setAttribute('aria-label','Play video');el.addEventListener('pointerenter',()=>el.controls=true);el.addEventListener('pointerleave',()=>{if(el.paused)el.controls=false;});el.addEventListener('focus',()=>el.controls=true);el.preload='none';el.playsInline=true;if(m.poster)el.poster=m.poster;position(el,m);el.addEventListener('click',e=>{e.stopPropagation();if(!el.controls){el.controls=true;el.play().catch(()=>status.textContent='Video playback failed.');}});overlays.append(el);}if(s.foreground){const fg=document.createElement('img');fg.src=s.foreground;fg.alt='';fg.style.cssText='inset:0;width:100%;height:100%;pointer-events:none';overlays.append(fg);}for(const link of s.links){const a=document.createElement('a');a.href=link.href;a.setAttribute('aria-label',link.href);if(!link.href.startsWith('#')){a.target='_blank';a.rel='noopener noreferrer';}position(a,link);a.addEventListener('click',e=>e.stopPropagation());overlays.append(a);}$('counter').textContent=`${index+1} / ${data.slides.length}`;status.textContent='';document.title=`CSID 2027 · ${index+1} / ${data.slides.length}`;for(const n of [index-1,index+1,index+2])load(n)?.ready.catch(()=>{});for(const n of cache.keys())if(n<index-1||n>index+2)cache.delete(n);updateNotes();}
function go(n){if(!data)return;n=Math.max(0,Math.min(data.slides.length-1,n));if(n!==index)location.hash=`slide-${n+1}`;}
function toggleOverview(){if(!data)return;if(overview.open){overview.close();return;}if(!$('grid').children.length)data.slides.forEach((s,i)=>{const b=document.createElement('button'),img=document.createElement('img');img.src=s.thumbnail;img.loading='lazy';img.alt=`Slide ${i+1}`;b.append(img,document.createTextNode(String(i+1)));b.addEventListener('click',()=>{go(i);overview.close();});$('grid').append(b);});[...$('grid').children].forEach((b,i)=>b.setAttribute('aria-current',String(i===index)));overview.showModal();$('grid').children[index].focus();}
async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch(e){status.textContent='Fullscreen is unavailable in this browser context.';}}
async function updateNotes(){if(!notesWindow||notesWindow.closed)return;try{const notes=await fetch('data/notes.json').then(r=>r.json());notesWindow.document.title='Private presenter notes';notesWindow.document.body.replaceChildren();const h=notesWindow.document.createElement('h1'),p=notesWindow.document.createElement('pre');h.textContent=`Slide ${index+1}`;p.textContent=notes[String(index+1)]||'No speaker notes for this slide.';p.style.whiteSpace='pre-wrap';notesWindow.document.body.append(h,p);}catch(e){}}
function notes(){notesWindow=window.open('about:blank','csid-private-notes','width=700,height=500');updateNotes();}
const actions={next:()=>go(index+1),previous:()=>go(index-1),overview:toggleOverview,fullscreen};$('controls').addEventListener('click',e=>{const action=e.target.closest('[data-action]');if(action)actions[action.dataset.action]();});$('close-overview').onclick=()=>overview.close();
document.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey)return;if(overview.open){if(e.key.toLowerCase()==='o'){e.preventDefault();overview.close();}return;}if(e.target.closest('video,audio,button,a'))return;const k=e.key.toLowerCase();const map={arrowright:()=>go(index+1),' ':()=>go(index+1),pagedown:()=>go(index+1),arrowleft:()=>go(index-1),pageup:()=>go(index-1),home:()=>go(0),end:()=>go(data.slides.length-1),f:fullscreen,o:toggleOverview,n:notes};if(map[k]){e.preventDefault();map[k]();}});
stage.addEventListener('pointerdown',e=>{if(!e.target.closest('video,audio,a'))start={x:e.clientX,y:e.clientY,id:e.pointerId};});stage.addEventListener('pointerup',e=>{if(!start||start.id!==e.pointerId)return;const dx=e.clientX-start.x,dy=e.clientY-start.y;start=null;if(Math.abs(dx)>50&&Math.abs(dx)>Math.abs(dy))go(index+(dx<0?1:-1));else if(Math.abs(dx)<12&&Math.abs(dy)<12)go(index+(e.clientX<innerWidth*.25?-1:1));});stage.addEventListener('pointercancel',()=>start=null);document.addEventListener('pointermove',activity);window.addEventListener('hashchange',render);
try{const response=await fetch('data/slides.json');if(!response.ok)throw Error(response.status);data=await response.json();canvas.style.width=`min(100vw,${data.aspectRatio*100}vh)`;canvas.style.height=`min(100vh,${100/data.aspectRatio}vw)`;await render();}catch(e){status.textContent='Unable to load presentation. Serve this folder with python -m http.server 8000.';}
})();
